### ISSUE TITLE
Add english translation

### ISSUE THREAD

**Issue by junwonp** [junwonp/next.js-blog#412]
### 세부 목적 (주 목적은 이슈 이름으로.)

일부 텍스트에 영어 번역 추가

### 예상 난이도는?

Easy but time-consuming

### 개발 계획

next-translate 패키지 설치

**Comment by Julrum** [comment]
Next.js Static HTML Export에서는 i18n 지원하지 않음

[https://nextjs.org/docs/advanced-features/static-html-export](https://nextjs.org/docs/advanced-features/static-html-export)
